#!/bin/sh

# aliases
alias pong="ping -c 3 www.google.ca"
alias wget="wget --hsts-file="$XDG_CACHE_HOME/wget-hsts""
alias ..="cd .."
alias getpath="find -type f | fzf | sed 's/^..//' | tr -d '\n' | xclip -selection c"
alias ls="exa --icons -a --group-directories-first"
alias nnn="nnn -c"
alias install-pacman="pacman -Slq | fzf --multi --prompt='install > ' --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias remove-pacman="pacman -Qq | fzf --multi --prompt='uninstall > ' --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"
alias pacinfo="pacman -Qq | fzf --multi --prompt='package > ' --preview 'pacman -Qil {1}' | xargs -ro pacman -Qil"
alias pacinfo-aur="pacman -Qqm | fzf --multi --prompt='package > ' --preview 'pacman -Qil {1}'"
alias tmux="tmux -f $XDG_CONFIG_DIR/tmux/tmux.conf"
alias tsp-backup="TS_SOCKET=/tmp/backup tsp"
alias tsp-fiio="TS_SOCKET=/tmp/fiio tsp"
alias v="$EDITOR"
alias yt-song="youtube-dl -x --audio-format flac --audio-quality 0"
alias zshreload="source ~/.zshrc"
alias wifi="nmtui"
alias typeless='history n 20000 | sed "s/.*  //"  | sort | uniq -c | sort -g | tail -n 100'
alias synctunes='rsync -a --delete --info=progress2 Storage/Tunes /run/media/andrew/6463-3832; notify-send -t 0 "Tunes synced my dude!"'
alias localip='hostname -i'

# Manage dotfiles with git bare repository
# https://www.atlassian.com/git/tutorials/dotfiles
alias config='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
alias config-add='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME add'
alias config-update='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME commit -am "update"'
alias config-push='/usr/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME push'
# config add /path/to/file
# config commit -m "A short message"
# config push

