#!/bin/bash
time="$1"

if [ -z "$time" ]
then
  xset -dpms ; notify-send "Sleep time mother fucker!" ; sleep 55m && systemctl suspend -i
else
  xset -dpms ; notify-send "DPMS is off and sleep timer is set for $time min" ; sleep "$time"m && systemctl suspend -i
fi


